# Generated by Django 4.2.1 on 2023-06-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('link_access', models.CharField(max_length=100)),
                ('date_record', models.DateField()),
            ],
        ),
    ]
